QA-61 | Card Payment UI Tests
Judopay/JudoKit-iOS pull request #197
Opened 2023-07-17 08:55 UTC by eugenezhernakov

* Populate with similar UI tests to Android
* Add environment variables to test scheme
* Move strings to separate file

2023-07-17 13:24 UTC, eugenezhernakov commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/CardPayment/CardPaymentUITests.swift
> +        app.cardDetailsSubmitButton?.tap()
Same as [above](https://github.com/Judopay/JudoKit-iOS/pull/197/files#r1265346214)

2023-10-11 08:43 UTC, stefan-tudor commented on fastlane/Matchfile
> +username("eugene.zhernakov@judopayments.com") # Your Apple Developer Portal username
worth injecting this as an env variable instead

2023-10-18 08:39 UTC, eugenezhernakov commented on fastlane/Matchfile
> +username("eugene.zhernakov@judopayments.com") # Your Apple Developer Portal username
Done

2023-10-18 10:58 UTC, eugenezhernakov commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/CardPayment/CardPaymentUITests.swift
> +func assertResultObject(_ app: XCUIApplication, _ type: String, _ message: String, _ result: String) {
Moved to separate file

2023-10-25 15:47 UTC, RafalOzogJudopay commented on Examples/ObjectiveCExampleApp/fastlane/.env
> +# oclint
Just cosmetic suggestion: maybe we don't need these "# gym", "# scan", "# slather", "# oclint" commented out titles in 4, 7, 14 and 20 lines - as it is repeated at the beginning of these constants anyway.

2023-10-25 15:48 UTC, RafalOzogJudopay commented on Examples/ObjectiveCExampleApp/fastlane/Matchfile
> +username(ENV["APPLE_DEV_ACCOUNT"]) # Your Apple Developer Portal username
Cosmetic, but probably we can remove this "# Your Apple Developer Portal username"

2023-10-25 16:03 UTC, RafalOzogJudopay commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/Helpers.swift
> +    while completeButton.exists && retryCount < 2 {
Is that correct that we expect two clicks in this case?

2023-10-25 16:09 UTC, eugenezhernakov commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/Helpers.swift
> +    while completeButton.exists && retryCount < 2 {
Unfortunately yes due to Global Pay sandbox environment, one click just refreshes the page.

2023-10-26 08:51 UTC, RafalOzogJudopay commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/Helpers.swift
> +    while completeButton.exists && retryCount < 2 {
That's fine. Maybe we could add some 1-liner comment about it in the code, if you'd like.

2023-10-26 08:53 UTC, eugenezhernakov commented on fastlane/Matchfile
> +username("eugene.zhernakov@judopayments.com") # Your Apple Developer Portal username
I believe Stefan is making changes in this file as part of `improvements/ci-with-fastlane` branch and it's already been updated, just needs to sync with this branch =)

2023-10-26 08:57 UTC, RafalOzogJudopay commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/XCUIApplication+Additions.swift
> +        }
Maybe we could extract these buttons labels into constants, if you have time to do so. If you're busy, let's leave as it is.

2023-10-26 08:58 UTC, eugenezhernakov commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/Helpers.swift
> +    while completeButton.exists && retryCount < 2 {
I've added a comment for this

2023-10-26 08:59 UTC, eugenezhernakov commented on Examples/ObjectiveCExampleApp/fastlane/.env
> +# oclint
@stefan-tudor do you use these env vars?

2023-10-26 09:00 UTC, eugenezhernakov commented on Examples/ObjectiveCExampleApp/fastlane/Matchfile
> +username(ENV["APPLE_DEV_ACCOUNT"]) # Your Apple Developer Portal username
Done

2023-10-26 09:02 UTC, RafalOzogJudopay requested changes
Overall, good code @eugenezhernakov 

Few brief points:

1. I left few comments about cosmetics (I leave it up to you to decide whether you would like to implement these changes or not), and 1 comment I would like you to have a look before I approve the PR (it's the comment about env variable in Matchfile). Please have a look.

2. I see this branch has some Fastlane setup files. Please ensure it won't collide with another Fastlane PR opened by Stefan this week (https://github.com/Judopay/JudoKit-iOS/pull/204).

3. I've seen your comment "Tried to assert that the snack bar is displayed with the expected message, but for some reason this doesn't work as it does above". Please do not hesitate to let me know if you would still need help with this, I am happy to help.

2023-10-26 09:47 UTC, eugenezhernakov commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/Additions/XCUIApplication+Additions.swift
> +        }
Done

2023-10-26 10:04 UTC, eugenezhernakov commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleAppUITests/CardPayment/CardPaymentUITests.swift
> +        app.deleteCardButton?.tap()
Added

2023-10-26 12:04 UTC, stefan-tudor approved these changes

2023-10-26 12:06 UTC, stefan-tudor commented on Examples/ObjectiveCExampleApp/fastlane/.env
> +# oclint
Yes, I cleaned it up a bit, some was unused

2023-10-26 13:06 UTC, RafalOzogJudopay approved these changes

2023-10-26 13:54 UTC, merged