CT-2824 Recurring Payment Adjustments
Judopay/JudoKit-iOS pull request #226
Opened 2024-01-11 10:22 UTC by RafalOzogJudopay

Missing validation of Recurring Payment configuration implemented on the SDK level.

2024-01-11 10:28 UTC, stefan-tudor commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +    if (configuration.applePayConfiguration.recurringPaymentRequest) {
Please reduce indentation, simply return early like so

```
if (!configuration.applePayConfiguration.recurringPaymentRequest) {
    return;
}
```

2024-01-11 10:44 UTC, stefan-tudor commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +            *error = JPError.missingRecurringIntervalUnitError;
probably `missingRecurringIntervaCountError` here instead of `missingRecurringIntervalUnitError`

2024-01-11 10:45 UTC, stefan-tudor commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +        if (!configuration.applePayConfiguration.recurringPaymentRequest.regularBilling.intervalUnit)
`intervalUnit` and `intervalCount` are primitive types, so you can't check them for null.

2024-01-11 14:21 UTC, RafalOzogJudopay commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +    if (configuration.applePayConfiguration.recurringPaymentRequest) {
Good point, fixed

2024-01-11 14:22 UTC, RafalOzogJudopay commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +        if (!configuration.applePayConfiguration.recurringPaymentRequest.regularBilling.intervalUnit)
Good catch, but has been removed anyway according to the next point

2024-01-11 14:22 UTC, RafalOzogJudopay commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +            *error = JPError.missingRecurringIntervalUnitError;
Good catch, but have been removed anyway according to the next point

2024-01-11 14:49 UTC, stefan-tudor commented on Examples/ObjectiveCExampleApp/Podfile.lock
> +COCOAPODS: 1.13.0
Please revert this and use `bundler` to run cocoa pods installs

`bundle exec pod install --repo-update`

2024-01-11 14:51 UTC, stefan-tudor commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +    if (!configuration.applePayConfiguration.recurringPaymentRequest)
This is preferable and consistent with the codebase; please use it instead

```
if (!configuration.applePayConfiguration.recurringPaymentRequest) {
    return;
}
```

instead of this 

```
if (!configuration.applePayConfiguration.recurringPaymentRequest)
    return;
```

2024-01-11 14:53 UTC, RafalOzogJudopay commented on Examples/ObjectiveCExampleApp/Podfile.lock
> +COCOAPODS: 1.13.0
Damn, right. I didn't notice this has been pushed, sorry, and thanks

2024-01-11 14:56 UTC, RafalOzogJudopay commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +    if (!configuration.applePayConfiguration.recurringPaymentRequest)
Hmm, I personally prefer to use the shorter form, wherever it's possible, but if you prefer the bracket's one - that's fine ;)

2024-01-11 14:58 UTC, stefan-tudor requested changes

2024-01-11 14:58 UTC, stefan-tudor commented on Source/Extensions/JPError/JPError+Additions.m
> +
you still have `missingRecurringIntervalCountError` and `missingRecurringIntervalUnitError`
if you don't need them anymore, please remove them from the codebase
otherwise, I think you can check `if (configuration.applePayConfiguration.recurringPaymentRequest.regularBilling.intervalUnit == 0)`

2024-01-11 15:07 UTC, RafalOzogJudopay commented on Source/Extensions/JPError/JPError+Additions.m
> +
correct, done

2024-01-12 10:29 UTC, stefan-tudor commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +    }
since this is the last statement, simply 

```
  if (!configuration.applePayConfiguration.recurringPaymentRequest.regularBilling.amount) {
        *error = JPError.missingRecurringAmountError;
    }
```

2024-01-12 10:30 UTC, stefan-tudor commented on Source/Extensions/JPError/JPError+Additions.h
> ++ (nonnull JPError *)missingRecurringIntervalUnitError;
you forgot to remove these two

2024-01-12 10:36 UTC, stefan-tudor commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Models/Settings.m
> +    return (description && ![description isEqualToString:@""]) ? description : nil;
simply:

`return description.length > 0 ? description : nil;`

2024-01-12 10:37 UTC, stefan-tudor commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Models/Settings.m
> +    return (managementUrl && ![managementUrl isEqualToString:@""]) ? managementUrl : nil;
simply:

return managementUrl.length > 0 ? managementUrl : nil;

2024-01-12 11:42 UTC, RafalOzogJudopay commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +    }
adjusted

2024-01-12 11:42 UTC, RafalOzogJudopay commented on Source/Extensions/JPError/JPError+Additions.h
> ++ (nonnull JPError *)missingRecurringIntervalUnitError;
adjusted

2024-01-12 12:15 UTC, RafalOzogJudopay commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Models/Settings.m
> +    return (description && ![description isEqualToString:@""]) ? description : nil;
corrected

2024-01-12 12:15 UTC, RafalOzogJudopay commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Models/Settings.m
> +    return (managementUrl && ![managementUrl isEqualToString:@""]) ? managementUrl : nil;
corrected

2024-01-12 12:15 UTC, RafalOzogJudopay commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Models/Settings.m
> +    return (billingAgreement && ![billingAgreement isEqualToString:@""]) ? billingAgreement : nil;
corrected

2024-01-12 13:26 UTC, stefan-tudor approved these changes

2024-01-12 16:27 UTC, merged