CT-2886: allowIncrement flag introduced
Judopay/JudoKit-iOS pull request #247
Opened 2024-05-16 12:19 UTC by RafalOzogJudopay

2024-05-16 12:42 UTC, RafalOzogJudopay commented on Examples/ObjectiveCExampleApp/ObjectiveCExampleApp/Settings.bundle/Root.plist
> +		<dict>
This is clang change that actually fixed margin for this one dict element (not related to this PR, but good anyway).

2024-05-16 12:42 UTC, RafalOzogJudopay commented on Source/Models/Request/JPPreAuthApplePayRequest.m
>      }
As headers of functions didn't change, I believe this solution is okay.

2024-05-22 08:38 UTC, RafalOzogJudopay commented
The one thing we were about to discuss (you wanted to have a look first @stefan-tudor) is how to assign default value for the new boolean. Let's not forget about it before merging.

2024-05-23 09:23 UTC, stefan-tudor commented on Source/Models/Configuration/JPConfiguration.h
> +@property (nonatomic, assign) BOOL isAllowIncrementOn;
For consistency, let's rename this to `isAllowIncrement`, there's no other flag suffixed with `On`

2024-05-23 09:32 UTC, stefan-tudor commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +    [self checkPreAuthPropertiesConfiguration:configuration transactionType:transactionType error:&error];
simply `checkPreAuthConfiguration`
and passing `transactionType` is redundant, simply add the check 
```
if transactionType == JPTransactionTypePreAuth then
   [checkPreAuthConfiguration:error:]
```

2024-05-23 09:33 UTC, stefan-tudor commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +    if (isSupportedTransactionType && arePreAuthPropertiesInConflict) {
These can be collapsed to:
```
if (configuration.isDelayedAuthorisation && configuration.isAllowIncrement)
```

2024-05-23 09:40 UTC, stefan-tudor requested changes
It looks good overall; excellent job!
Just a few minor remarks

2024-05-23 09:41 UTC, stefan-tudor commented on Source/Models/Request/JPPreAuthApplePayRequest.m
>      }
yup, looks good

2024-05-23 09:42 UTC, stefan-tudor commented
> The one thing we were about to discuss (you wanted to have a look first @stefan-tudor) is how to assign default value for the new boolean. Let's not forget about it before merging.

isn't it already sending pre auth requests with this property as false?

2024-05-23 13:06 UTC, RafalOzogJudopay commented on Source/Models/Configuration/JPConfiguration.h
> +@property (nonatomic, assign) BOOL isAllowIncrementOn;
Adjusted

2024-05-23 13:06 UTC, RafalOzogJudopay commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +    [self checkPreAuthPropertiesConfiguration:configuration transactionType:transactionType error:&error];
Adjusted

2024-05-23 13:06 UTC, RafalOzogJudopay commented on Source/Services/ConfigurationValidation/JPConfigurationValidationService.m
> +    if (isSupportedTransactionType && arePreAuthPropertiesInConflict) {
Adjusted

2024-05-23 13:09 UTC, RafalOzogJudopay commented
> > The one thing we were about to discuss (you wanted to have a look first @stefan-tudor) is how to assign default value for the new boolean. Let's not forget about it before merging.
> 
> isn't it already sending pre auth requests with this property as false?

Yes, it seems you're right. I've just tested this with debugger (commented out line that sets this boolean in configuration, and further in the code it had "NO" as a value).

2024-05-23 13:13 UTC, stefan-tudor approved these changes

2024-05-23 13:40 UTC, merged