Addresses reported ApplePay issues
Judopay/JudoKit-iOS pull request #258
Opened 2024-08-08 20:45 UTC by stefan-tudor

- adds missing Swift API attributes
- restricts JudoKit.new and JudoKit.init in favour of convenience initialisers
- minor updates of the ApplePay module
- SPM example - ApplePay examples added
- package major version bump

2024-08-09 08:01 UTC, eugenezhernakov approved these changes

2024-08-13 12:07 UTC, RafalOzogJudopay commented on Examples/SPMExampleApp/SPMExampleApp/Features/FeaturesView.swift
> +            .padding(.vertical, 4)
Suggestion: maybe we could avoid Button code duplication by making our custom button class (taking action and title as only arguments).

2024-08-13 14:02 UTC, RafalOzogJudopay requested changes

2024-08-13 14:02 UTC, RafalOzogJudopay approved these changes

2024-08-13 14:08 UTC, stefan-tudor commented on Examples/SPMExampleApp/SPMExampleApp/Features/FeaturesViewController.swift
> +        Task { [unowned self] in
signature of the functions is different, names are the same

2024-08-13 15:19 UTC, merged